version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports: 
      - "5432:5432"

  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    restart: always
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MODE=master

  spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    restart: always
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G

  spark-worker-2:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    restart: always
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G

  spark-submit:
    image: bde2020/spark-submit:2.4.4-hadoop2.7
    restart: always
    container_name: spark-submit
    depends_on:
      - spark-master
    volumes:
      - ./app:/app
    environment:
      - SPARK_MASTER=spark://spark-master:7077
